
FROM python:3.11-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install flask==2.2.2 

RUN pip install psycopg2-binary

RUN pip install gunicorn


COPY . /app

VOLUME ["/app"]

WORKDIR /app

RUN mkdir -p logs

EXPOSE 5000

CMD ["gunicorn","-b", "0.0.0.0:5000", "app:app"]